### ISSUE TITLE
Remove support for PHP5

### ISSUE THREAD

**Issue by nyamsprod** [TRowbotham/URL-Parser#2]
@TRowbotham  currently the parser still support PHP5 which will hit EOL at the end of the year. Do you plan on stopping PHP5 support anytime soon ?

**Comment by nyamsprod** [comment]
I'm asking because I was in the process of creating a similar library but since yours is already developpee I want to help by submitting some PR but targeting PHP5 or PHP7.0 seems to be a waste unless proven otherwise :thinking: thoughts?

**Comment by TRowbotham** [comment]
Given that both PHP 5 and 7.0 will hit EOL at the end of the year, I have no compelling reason to to continue supporting PHP 5 or PHP 7.0. I would gladly accept PRs targeting PHP 7.1.

**Comment by TRowbotham** [comment]
Support for PHP 5 was dropped with the 2.0.0 release.
